imports:
    - { resource: fancourier.yml }
    - { resource: sprinter.yml }

parameters:
    konekt_courier.form_type_resolver.class: Konekt\CourierBundle\Services\CarrierDetailsFormTypeResolver

services:
    konekt_courier.form_type_resolver:
        class: %konekt_courier.form_type_resolver.class%