konekt_courier_fancourier_create_awb:
    path: /courier/awb/create/fancourier/{packageId}
    methods: [GET, POST]
    defaults:
        _controller: KonektCourierBundle:Fancourier:createAwb

konekt_courier_fancourier_awb_show_details:
    path: /courier/awb/details/fancourier/{awbNumber}
    defaults:
        _controller: KonektCourierBundle:Fancourier:awbShowDetails

konekt_courier_fancourier_awb_show_pdf:
    path: /courier/awb/showPdf/{awbNumber}
    defaults:
        _controller: KonektCourierBundle:Fancourier:awbShowPdf

konekt_courier_fancourier_awb_show_html:
    path: /courier/awb/showHtml/{awbNumber}
    defaults:
        _controller: KonektCourierBundle:Fancourier:awbShowHtml

konekt_courier_fancourier_awb_delete:
    path: /courier/awb/delete/{awbNumber}
    defaults:
        _controller: KonektCourierBundle:Fancourier:awbDelete

konekt_courier_fancourier_test_awb_creation:
    path: /courier/testAwbCreation
    defaults:
        _controller: KonektCourierBundle:FancourierTest:testCreation

konekt_courier_fancourier_test_awb_deletion:
    path: /courier/testAwbDeletion/{awbNumber}
    defaults:
        _controller: KonektCourierBundle:FancourierTest:testDeletion

# DPD

konekt_courier_dpd_create_awb:
    path: /courier/awb/create/dpd/{packageId}
    methods: [GET, POST]
    defaults:
        _controller: KonektCourierBundle:Dpd:createAwb

konekt_courier_dpd_awb_show_details:
    path: /courier/awb/details/dpd/{awbNumber}
    defaults:
        _controller: KonektCourierBundle:Dpd:awbShowDetails

