services:
    konekt_courier.fancourier.api.credentials:
        class: Konekt\Courier\FanCourier\ApiCredentials
        arguments:
            - %konekt_courier.fancourier.api.username%
            - %konekt_courier.fancourier.api.user_pass%
            - %konekt_courier.fancourier.api.client_id%
        public: false