services:
    konekt_courier.fancourier.api.credentials:
        class: Konekt\Courier\FanCourier\ApiCredentials
        arguments:
            - %konekt_courier.fancourier.api.username%
            - %konekt_courier.fancourier.api.user_pass%
            - %konekt_courier.fancourier.api.client_id%

    konekt_courier.fancourier.command.factory:
        class: Konekt\Courier\FanCourier\Transaction\CommandFactory
        arguments:
            - "@konekt_courier.fancourier.api.credentials"

    konekt_courier.fancourier.request.processor:
        class: Konekt\Courier\Common\RequestProcessor
        arguments:
            - "@konekt_courier.fancourier.command.factory"

    konekt_courier.dpd.api.credentials:
        class: Konekt\Courier\Dpd\ApiCredentials
        arguments:
            - %konekt_courier.dpd.api.username%
            - %konekt_courier.dpd.api.password%

    konekt_courier.dpd.command.factory:
        class: Konekt\Courier\Dpd\Transaction\CommandFactory
        arguments:
            - "@konekt_courier.dpd.api.credentials"

    konekt_courier.dpd.request.processor:
        class: Konekt\Courier\Common\RequestProcessor
        arguments:
            - "@konekt_courier.dpd.command.factory"