services:
    konekt_courier.sprinter.command.factory:
        class: Konekt\Courier\Sprinter\PartnerToPudo\Transaction\CommandFactory

    konekt_courier.sprinter.request.processor:
        class: Konekt\Courier\Common\RequestProcessor
        arguments:
            - "@konekt_courier.sprinter.command.factory"