konekt_courier_fancourier_create_awb:
    path: /awb/create/{packageId}
    methods: [GET, POST]
    defaults:
        _controller: KonektCourierBundle:Fancourier:createAwb

konekt_courier_fancourier_awb_show_details:
    path: /awb/details/{awbNumber}
    defaults:
        _controller: KonektCourierBundle:Fancourier:awbShowDetails

konekt_courier_fancourier_awb_show_pdf:
    path: /awb/showPdf/{awbNumber}
    defaults:
        _controller: KonektCourierBundle:Fancourier:awbShowPdf

konekt_courier_fancourier_awb_show_html:
    path: /awb/showHtml/{awbNumber}
    defaults:
        _controller: KonektCourierBundle:Fancourier:awbShowHtml

konekt_courier_fancourier_awb_delete:
    path: /awb/delete/{awbNumber}
    defaults:
        _controller: KonektCourierBundle:Fancourier:awbDelete

konekt_courier_fancourier_test_awb_creation:
    path: /testAwbCreation
    defaults:
        _controller: KonektCourierBundle:FancourierTest:testCreation

konekt_courier_fancourier_test_awb_deletion:
    path: /testAwbDeletion/{awbNumber}
    defaults:
        _controller: KonektCourierBundle:FancourierTest:testDeletion